### PR TITLE
added satellite_provider field and stubbed in anonymous_proxy

### PR DESCRIPTION
**Pull request by mhess-connectify**
Exposed is_satellite_provider field.  Added stubs for is_anonymous_proxy, but it doesn't work yet.

### CODE REVIEW

**Comment by fiorix** [comment]
This would break backwards compatibility with the csv output. I've been thinking about dropping that (the /csv) since it causes more trouble than benefits. Will leave this here until I have a clear opinion about what to do with this situation.

**Comment by mhess-connectify** [comment]
Ah, thanks for the response.  CSV output looks ok to me. I tried a satellite provider IP and got the following:

XML:
<?xml version="1.0" encoding="UTF-8"?>
<Response>
	<IP>217.194.145.164</IP>
	<CountryCode></CountryCode>
	<CountryName></CountryName>
	<RegionCode></RegionCode>
	<RegionName></RegionName>
	<City></City>
	<ZipCode></ZipCode>
	<TimeZone></TimeZone>
	<Latitude>0</Latitude>
	<Longitude>0</Longitude>
	<MetroCode>0</MetroCode>
	<IsSatelliteProvider>true</IsSatelliteProvider>
</Response>

JSON:
{"ip":"217.194.145.164","country_code":"","country_name":"","region_code":"","region_name":"","city":"","zip_code":"","time_zone":"","latitude":0,"longitude":0,"metro_code":0,"is_satellite_provider":true}

CSV:
217.194.145.164,,,,,,,,true,0.00,0.00,0

Are you saying it breaks support for users already consuming the existing version?

Also, do you have a guess why is_anonymous_proxy isn't returning the correct values with my stubs? Following the maxmind documentation, it looks like it should work.

**Comment by fiorix** [comment]
Yes, people that currently consume from the /csv endpoint would have their software broken. I don't know about the anonymous proxy, haven't looked into that before. Maybe someone from MaxMind would know better.

**Comment by mhess-connectify** [comment]
Hmm, what do you think about versioned routes?  That's often recommended for REST anyway.

**Comment by fiorix** [comment]
That's right, I've been thinking about adding a /v2/json only, with all new goodies. Someone else asked for continent information the other day, now there's this one, so maybe that's the way to go. I don't think it's important to support xml and csv in the new version unless someone really needs that.

**Comment by fiorix** [comment]
no plans to support /v2 now

**Pull request closed without merging**
