### PR TITLE
Updating deprecated base image | Adding some comments	

### PR DESCRIPTION
**Pull request by dam660**
Hi,

google/golang is deprecated, I replaced it by golang:1.5 and added some comments.

### CODE REVIEW

**Comment by palamccc** [comment]
+1, waiting for this to get merged, old docker image is too big, 620Mb, i hope this will be smaller.

**Comment by ApfelUser** [comment]
+1

**Comment by fiorix** [comment]
+1

**Comment by palamccc** [comment]
Docker image download size is still 242MB https://hub.docker.com/r/fiorix/freegeoip/tags/
The docker size is big, because it contains base os + golang tools + freegeoip source + compiled freegeoip. But to run freegeoip, freegeoip binary alone is enough.

I tried to create a docker with only freegeoip binary and got it working, it directly downloads release binary from github.
https://github.com/palamccc/freegeoip-docker/blob/master/Dockerfile

The docker image size is 50Mb (busybox + freegeoip binary) https://hub.docker.com/r/palamccc/freegeoip-docker/tags/ I don't know whether this right way to design Dockerfile, just posting it here for your review.

**Pull request merged**
