### PR TITLE
adding newrelic

### PR DESCRIPTION
**Pull request by omercnet**
newrelic support for those who are looking for simpler metrics without setting up a prometheus server

### CODE REVIEW

**Comment by fiorix** [comment]
Travis failing due to no space on disk 🤣

**Comment by omercnet** [comment]
lol, travis doesn't seem to like my PRs :)

**Comment by fiorix** [comment]
I have restarted the build there. Let's see. :)

**Comment by fiorix** [comment]
Nice, thank you. I changed the commit message to conform to this: http://chris.beams.io/posts/git-commit/

**Pull request merged**
