### PR TITLE
Add the possibility to read config from env

### PR DESCRIPTION
**Pull request by pierreozoux**
Hi!

This is my first PR in go, I'll need some help to go though.
I just have one question, how to properly use the logger?

I reused the code from etcd.

Hope you like it :)

### CODE REVIEW

**Comment by fiorix** [comment]
Hey this is a good start. Your patch is suffering from the context vs old-context packages mismatch, and the only easy way to fix it is by removing support for old Go versions in the .travis.yml config at the root of the repository. I believe we can drop support for Go older than 1.7.

Aside from this, have you looked at https://github.com/kelseyhightower/envconfig ?

This would simplify your diff a lot, because you could just add tags to the Config struct in apiserver/config.go and a hook to load them up.

**Comment by fiorix** [comment]
I have just fixed the first part, which is to remove support for old Go versions.

**Comment by pierreozoux** [comment]
Thanks for the feedback, just reopened a new PR.

**Comment by fiorix** [comment]
👍

**Pull request closed without merging**
