### PR TITLE
Add support for ISO ALPHA-3 country codes

### PR DESCRIPTION
**Pull request by alaska**
Taken from http://download.geonames.org/export/dump/countryInfo.txt

### CODE REVIEW

**Comment by fiorix** [comment]
Hey @alaska this is nice, but is backwards incompatible for the CSV API and would break clients... falls into the same as https://github.com/fiorix/freegeoip/issues/107, and https://github.com/fiorix/freegeoip/pull/111. Will keep this here and whenever there's a strategy for a /v2 thing it can be merged in. For now, nothing prevents clients to implementing this logic.

**Comment by alaska** [comment]
Could always place it on the end.

**Comment by fiorix** [comment]
This CSV API only brings trouble... It's shocking that such format is currently 25-35% of all traffic of freegeoip.net, which delivers over 2 billion responses per day.

**Comment by alaska** [comment]
That's fair.  In consulting with a coworker I've learned that at least some of the maxmind binary databases provide country-3.  If this is the case for the DB you pull, all this was bollocks anyway and I'll revert.  Will return when I'm sure.

**Comment by fiorix** [comment]
If it's supported, is probably here: https://github.com/oschwald/geoip2-golang/blob/master/reader.go

Maybe @oschwald knows better.

**Comment by oschwald** [comment]
The MaxMind GeoIP2 databases only provide the two letter ISO codes.

**Comment by alaska** [comment]
Was just writing that.  Looks like it's only in the legacy.

**Comment by alaska** [comment]
Couple of ideas

1) Simply comment it out of the CSV output and let folks use another format if they want country-3
2) Allow an optional param to specify a 3-letter country code vs the 2-letter one.

Thoughts?

**Comment by fiorix** [comment]
Still think it's better to have all changes (not only yours) in a /v2 endpoint, that only supports json. That's probably what I'm going to do for the long term.

**Comment by alaska** [comment]
Fair enough. We'll let it sit for now.

**Comment by fiorix** [comment]
no plans to support /v2 now

**Pull request closed without merging**
