### PR TITLE
added heroku support

### PR DESCRIPTION
**Pull request by omercnet**
in the effort of motivating people to launch their own instance of freegeoip, this adds the ability to "deploy to heroku" with a single click

### CODE REVIEW

**Comment by fiorix** [comment]
This one is unexpected: https://travis-ci.org/fiorix/freegeoip/jobs/189379740

**Comment by fiorix** [comment]
Any chance you can use https://github.com/kardianos/govendor instead of godep? I've used both in the past but lately have settled on govendor for a number of reasons.. the first being it doesn't create another directory at the root level of your repo, and places its file under vendor/; also it has a much better cmdline interface.

**Comment by omercnet** [comment]
yea no problem, godep is default on heroku so I used that 
will update soon

**Comment by omercnet** [comment]
fixed and rebased with master

**Comment by fiorix** [comment]
💯

**Pull request merged**
